project:
  type: website
  title: "pure_mediation"
  output-dir: _site
  resources:
    - fonts
    
website:
  site-url: https://puremediation.netlify.app

format:
  revealjs:
    theme: [default, custom-fonts.scss]